sources:
  - name: sports_db_raw
    database: sports_db
    schema: raw
    tables:
    - name: football_data__areas
      description: "Areas table as extracted from the football-data API"
    - name: football_data__competitions
      description: "Competitions table as extracted from the football-data API"
    - name: football_data__teams
      description: "Teams table as extracted from the football-data API"
    - name: football_data__matches
      description: "Matches table as extracted from the football-data API"
    - name: football_data__players
      description: "Players table as extracted from the football-data API"
